FROM apache/spark:3.5.3

USER root

# Install Java 11 and pip
RUN apt-get update && apt-get install -y python3-pip openjdk-11-jdk && \
    pip3 install pyspark==3.5.3

# Add Hadoop AWS + AWS SDK (required for MinIO)
RUN curl -L -o /opt/spark/jars/hadoop-aws-3.3.4.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    curl -L -o /opt/spark/jars/aws-java-sdk-bundle-1.12.530.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.530/aws-java-sdk-bundle-1.12.530.jar

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

USER spark

WORKDIR /app
